export const paths = {
  signIn: "/login",
  home: "/",
  teams: "/teams",
  create: "/create",
  players: "/players",
  draw: "/draw",
  match: "/match",
  matchResult: "/match/result",
  history: "/history",
  summary: "/summaries",
  organize: "/match/organize",
  installApp: "/install",
  suggestions: "/suggestions",
  feedbacks: "/feedbacks",
  landingPage: "/landing-page",
} as const;
